### ISSUE TITLE
[BUG] Speed keeps dropping to minimum

### ISSUE THREAD

**Issue by richb-hanover** [sqm-autorate/sqm-autorate#119]
**Script Version** 0.4.4

**Describe the bug**
My speeds to the CAKE keep dropping to the minimum value configured when the line is idle. This was earlier diagnosed as being caused by latency spikes. (I had reported this earlier, but closed that issue because it was for an enormously old version.) Here's a chart:

![timeseries](https://user-images.githubusercontent.com/1094930/149792595-1f1a4cf4-1204-4fae-b828-1b208d548c96.png)

Diagnostic info is in: [openwrtstats-2022-01-14-075541.gz](https://github.com/sqm-autorate/sqm-autorate/files/7882762/openwrtstats-2022-01-14-075541.gz)

**To Reproduce**
1. Use remove.sh and setup.sh scripts from `lua-threads` branch
2. Set upload and download nominal values; accept default of 20%
3. Let it run. _sqm-autorate_ adapts to traffic as expected.
4. Go away, come back. Often the speed settings have been reset to minimums
5. Generate more traffic (either test traffic or actual use). _sqm-autorate_ bumps up as required, so that a speed test  gives >>90% of the rated link speed.

**Expected behavior**
No sudden decreases in speed settings to CAKE

**Screenshots**
See above

**OpenWrt Details (please paste your output from `cat /etc/os-release`):**
 - OS-Release: 21.02.1
 - Connection Type + Speed: 25mbps symmetric

**Additional context**
See all the debugging files in the zip file above

**Comment by chas-iot** [comment]
My understanding is that this is functioning as designed.  I’m commenting here so that, whether my understanding here is correct or not, we can update the documentation.

If there is a latency spike (even transient) when there is low/no load, then the rate is dropped to minimum. In compensation, as soon as there is load and no delay, the speed will be hiked instantly.

**Comment by richb-hanover** [comment]
Thanks for the follow-up. Other thoughts:

1. I'm reporting the behavior to see if that matches what we think it should do. 
2. But I'm only reporting, not complaining. From a user standpoint, the CAKE settings ramp up quickly (nearly immediately) in normal use.
3. Any ideas why the latency spikes so regularly? I count about 35 regularly spaced spikes across the ~10 hours of the chart, or a few per hour. (I do have a program that regularly runs a speed test every 30 minutes - could that account for some?)

Thanks.

**Comment by chas-iot** [comment]
> 3\. Any ideas why the latency spikes so regularly?
Checking the graph, the load goes above 1 and often as far as 1.25,. The regularity and the load are strongly indicative that the cause is the speed test you mentioned.

Remember that the load reported in the graph is relative to the CAKE speed set by sqm-autorate at that moment, and is not relative to the current capacity of the connection to the ISP. This distinction is (I believe) important to the working of sqm-autorate.

**Comment by richb-hanover** [comment]
I think this can be closed. The age of this code branch, plus the traffic spikes from my own particular environment make it less than useful to keep open. 

I will re-open if I see odd things happening again.
