### ISSUE TITLE
[BUG] installation procedure fails

### ISSUE THREAD

**Issue by chas-iot** [sqm-autorate/sqm-autorate#189]
installation process fails, likely due to change in the github api, possibly anonymous access no longer supported

`sh -c "$(wget -q -O- https://raw.githubusercontent.com/sqm-autorate/sqm-autorate/main/sqm-autorate-setup.sh)"`
`>>> Refreshing package cache. This may take several minutes...`
`>>> Installing required packages via opkg...`
`>>> Installing required packages via luarocks...`
`Installing https://luarocks.org/vstruct-2.1.1-1.src.rock...`
`Using https://luarocks.org/vstruct-2.1.1-1.src.rock... switching to 'build' mode`
`Updating manifest for /usr/lib/luarocks/rocks`
`vstruct 2.1.1-1 is now built and installed in /usr`

`>>> Creating /usr/lib/sqm-autorate`
`>>> Downloading sqm-autorate files...`
`tar: can't open '/tmp/sqm-autorate-install.tar.gz': No such file or directory`

On checking, I found that the URL is rejected in curl
`curl: (3) URL rejected: Error`
however in the browser, the same URL works `https://api.github.com/repos/sqm-autorate/sqm-autorate/tarball/main`

**Comment by Lochnair** [comment]
@chas-iot I already got this fixed in #184, the error is a bit misleading. The parameters to cURL was swapped, so it's trying to use the local path as the URL

I was intending to merge this and other changes to main, but ran into some merge conflicts.
And I'm not quite sure what's the best way to get it fixed

**Comment by Lochnair** [comment]
Should be good now after new release
